In [1]:
import random

position = 0
walk = [ position ]#그때 그때 position에 대해 기록할 list
steps = 1000 #1000보 걸음

for i in range(steps):
    step = 1 if random.randint(0,1) else -1
    position += step
    walk.append(position)

print(walk)


[0, 1, 0, 1, 2, 1, 0, -1, -2, -1, 0, -1, -2, -1, 0, 1, 2, 3, 2, 1, 0, -1, 0, 1, 2, 3, 4, 5, 6, 5, 4, 5, 6, 7, 8, 9, 10, 11, 12, 11, 12, 11, 10, 11, 10, 11, 12, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 19, 20, 21, 22, 21, 22, 21, 20, 21, 22, 23, 24, 23, 24, 25, 26, 27, 28, 27, 26, 27, 26, 25, 24, 25, 24, 25, 26, 27, 28, 27, 28, 29, 28, 27, 28, 27, 26, 25, 24, 25, 26, 27, 28, 29, 28, 29, 30, 29, 30, 31, 32, 31, 30, 31, 30, 31, 30, 29, 28, 29, 30, 29, 28, 27, 26, 27, 26, 25, 26, 25, 26, 27, 28, 29, 28, 27, 26, 25, 26, 25, 26, 25, 26, 27, 28, 27, 28, 27, 26, 25, 26, 25, 26, 27, 26, 25, 26, 25, 24, 25, 26, 25, 24, 25, 24, 23, 22, 23, 24, 25, 26, 27, 26, 25, 24, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 32, 31, 32, 33, 34, 35, 36, 37, 36, 35, 34, 33, 34, 35, 34, 35, 36, 35, 34, 35, 36, 37, 36, 37, 38, 39, 40, 39, 40, 39, 40, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 48, 49, 48, 49, 50, 49, 48, 49, 50, 51, 52, 53, 52, 53, 54, 53, 52, 51, 50, 51, 50, 51, 50, 49, 50, 49, 48, 47, 48, 49, 50, 

python 2    vs  python 3

xrange(10)  |  range(10)

range(10)   |  list(range(10))

In [2]:
#numpy를 통해 똑같은걸 간략하게 나타낼 수 있다...

import numpy as np
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0 , 1, -1) #draws > 0 이면 1, <=0 이면 -1로 추정
walk = steps.cumsum()

walk

array([ -1,   0,   1,   2,   1,   2,   1,   2,   3,   2,   3,   4,   5,
         6,   5,   6,   5,   6,   5,   6,   5,   4,   5,   6,   7,   8,
         9,  10,   9,   8,   9,  10,   9,  10,   9,   8,   7,   6,   7,
         8,   7,   8,   7,   8,   7,   6,   5,   6,   7,   8,   7,   8,
         9,   8,   7,   6,   7,   6,   5,   6,   5,   6,   5,   6,   7,
         6,   5,   4,   3,   4,   5,   6,   7,   8,   7,   8,   7,   6,
         7,   8,   9,   8,   9,   8,   9,  10,  11,  10,   9,   8,   9,
         8,   7,   6,   5,   4,   5,   6,   5,   4,   5,   6,   5,   6,
         7,   6,   7,   8,   7,   8,   7,   6,   7,   6,   7,   6,   7,
         8,   9,  10,   9,  10,   9,  10,  11,  12,  13,  14,  13,  14,
        15,  16,  15,  14,  13,  14,  13,  14,  15,  14,  15,  16,  15,
        16,  17,  18,  19,  20,  19,  18,  19,  20,  19,  18,  19,  18,
        19,  18,  19,  20,  21,  22,  21,  22,  21,  22,  23,  22,  23,
        22,  23,  22,  21,  20,  21,  22,  21,  22,  21,  20,  1

In [ ]:
#위의꺼 소규모로 검증해보기

import numpy as np
nsteps = 30
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0 , 1, -1) #draws > 0 이면 1, <=0 이면 -1로 추정
walk = steps.cumsum()

print(draws)
print(steps)
walk

In [3]:
print(walk.min())
print(walk.max())
print( (np.abs(walk) >= 10).argmax() )

-10
37
27


In [4]:
#좀 더 판을 키움

nwalks = 5000
nsteps = 1000

draws = np.random.randint(0, 2, size=(nwalks, nsteps)) # 0 or 1로 난수 생성, 크기는 nwalks x nsteps
steps = np.where(draws>0, 1, -1) #1이면 steps=1, 0이면 steps=-1
walks = steps.cumsum(1) #steps의 누적합..???????인자 1은 뭐지

walks

array([[  1,   2,   3, ...,  22,  23,  22],
       [  1,   0,   1, ...,  -8,  -7,  -6],
       [  1,   2,   3, ...,  12,  13,  12],
       ...,
       [  1,   0,  -1, ..., -44, -43, -44],
       [  1,   2,   3, ...,  -8,  -7,  -6],
       [  1,   2,   1, ...,  54,  55,  54]])

In [5]:
hits30 = (np.abs(walks) >= 30).any(1) 
hits30

array([ True,  True, False, ...,  True, False,  True])

In [6]:
hits30.sum() #number that hit 30 or -30

3316

In [ ]:
crossing_times = (np.abs(walks[hits30])>=30).argmax(1)
crossing_times

In [ ]:
crossing_times.mean()

In [ ]:
steps = np.random.normal(loc = 0, scale = 0.25, size=(nwalks, nsteps))
steps
#다른 난수발생 함수를 쓰면 정규분포형태로 만들 수도 있겠다