# 연습문제

In [1]:
import numpy as np

n의 제곱수로 2 dimentional array를 생성하는 ndarray.

Args

- n: 생성하고자 하는 ndarray의 row와 column의 개수
- dtype: 생성하려는 ndarray의 data type (np.int)

Returns

row와 column의 길이가 n인 two dimentional ndarray로 X[0,0]은 0으로 순차적으로 X[n-1,n-1]은 n^2-1이 할당됨

In [2]:
def n_size_ndarray_creation(n,dtype=np.int):
    arr = np.arange(n**2).reshape(n,n)
    return arr

def n_size_ndarray_creation2(n,dtype=np.int):
    return np.array(range(n**2), dtype = dtype).reshape(n,n)

In [3]:
n_size_ndarray_creation(3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
n_size_ndarray_creation2(4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

shape이 지정된 크기의 ndarray를 생성,

이때 행렬의 element는 type에 따라 0, 1 또는 empty로 생성됨.

Args
- shape: 생성할려는 ndarray의 shape
- type: 생성되는 element들의 값을 지정함0은 0, 1은 1, 99는 empty 타입으로 생성됨
- dtype: 생성하려는 ndarray의 data type (np.int)

Returns

shape의 크기로 생성된 ndarray로 type에 따라 element의 내용이 변경됨


Examples

**zero_or_one_or_empty_ndarray(shape=(2,2), type=1)**

array(\[[ 1,  1],[ 1,  1]\])

**zero_or_one_or_empty_ndarray(shape=(3,3), type=99)**

임의의수 생성

array(\[[1773984320,        487, 1774114944],
        [       487, 1947927088,          0],
        [1947927088,          0, 1701605485]\])

In [ ]:
def zero_or_one_or_empty_ndarray(shape,type,dtype=np.int):
    if type == 0:
        return np.zeros(shape = shape, dtype = dtype)
    
    if type == 1:
        return np.ones(shape = shape, dtype = dtype)
    
    if type == 99:
        return np.empty(shape = shape, dtype = dtype)

In [ ]:
zero_or_one_or_empty_ndarray((2,3),1)

def change_shape_of_ndarray(X, n_row):

    return X
    
목적
- 입력된 ndarray X row의 개수를 n_row로 지정한 matrix를 반환함.
- 이때 입력하는 X의 size는 2의 거듭제곱수로 전제함.
- 만약 n_row = 1일 때는 matrix가 아닌 vector로 반환함.

Args
- X: 입력하는 ndarray
- n_row: 생성할려는 matrix의 row의 개수

Returns

- row의 개수가 n_row인 Matrix 또는 Vector
- n_row가 1이면 Vector 값으로 반환함 ~~=>무시해버렸음..~~


Examples

import numpy as np

import numpy_lab as testcode

X = np.ones((32,32), dtype=np.int)

testcode.change_shape_of_ndarray(X, 1)

array([1, 1, 1, ..., 1, 1, 1])

testcode.change_shape_of_ndarray(X, 512)

array([[1, 1],
       [1, 1],
       [1, 1],
       ...,
       [1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
def change_shape_of_ndarray(X, n_row):
    X = X.reshape(n_row,int(np.size(X)/n_row))
    return X

In [ ]:
X = np.arange(16).reshape(2,8)
X

In [ ]:
change_shape_of_ndarray(X, 1)

In [ ]:
change_shape_of_ndarray(X,4)

In [ ]:
def change_shape_of_ndarray2(X, n_row):

    return X.flatten() if n_row == 1 else X.reshape(n_row, -1)

In [ ]:
X = np.arange(32).reshape(2,16)
X

In [ ]:
change_shape_of_ndarray2(X,4)

입력된 vector type의 ndarray X에서 target_value와 가장 차이가 작게나는 element를 찾아 리턴함

이때 X를 list로 변경하여 처리하는 것은 실패로 간주함.

Args
- X: 입력하는 vector type의 ndarray
- target_value : 가장 유사한 값의 기준값이 되는 값

Returns
- target_value와 가장 유사한 값

Examples

import numpy as np

import numpy_lab as testcode

X = np.random.uniform(0, 1, 100)

target_value = 0.3

testcode.find_nearest_value(X, target_value)

    0.29260674329282488 #출력되는 값은 random 하게 바뀜

In [ ]:
def find_nearest_value(X, target_value):
    return X[np.argmin(np.abs(X-target_value))]

In [ ]:
X = np.random.uniform(0, 1, 5)
X

In [ ]:
find_nearest_value(X, 0.4)