## numpy 모듈의 호출

In [1]:
import numpy as np

#### array의 생성

In [8]:
test_array = np.array(["1", "4", 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [9]:
type(test_array[3])

numpy.float64

In [10]:
test_array = np.array([1, 4, 5, "8"], np.float32) # String Type의 데이터를 입력해도
test_array

array([1., 4., 5., 8.], dtype=float32)

In [4]:
#np.dtype('i4') == np.int32

np.array([1,2,3], dtype=np.dtype('i4'))

array([1, 2, 3], dtype=int32)

In [11]:
type(test_array[3])   # Float Type으로 자동 형변환을 실시

numpy.float32

In [12]:
test_array.dtype   # Array(배열) 전체의 데이터 Type을 반환함

dtype('float32')

In [13]:
np.array([[1, 4, 5, "8"]], np.float32).shape

(1, 4)

In [14]:
test_array.shape   # Array(배열) 의 shape을 반환함

(4,)

#### arrary shape

In [15]:
vector  = [1,2,3,4]
np.array(vector, int).shape

(4,)

In [16]:
matrix  = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [17]:
tensor  = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(4, 3, 4)

In [18]:
np.array(tensor, int).ndim

3

In [19]:
np.array(tensor, int).size

48

#### numpy dtype

In [29]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], dtype=int)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

In [23]:
np.array([[1, 2, 3], [4.5, "5", "6"]], 
         dtype=np.float32).nbytes

24

In [24]:
np.array([[1, 2, 3], [4.5, "5", "6"]], 
         dtype=np.int8).nbytes

6

In [25]:
np.array([[1, 2, 3], [4.5, "5", "6"]], 
         dtype=np.float64).nbytes

48

####  reshape

In [26]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [27]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [8]:
arr = np.arange(15)
arr.reshape((3,5))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
test =np.array(test_matrix).reshape(8,)
test

array([1, 2, 3, 4, 1, 2, 5, 8])

In [30]:
test.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [1],
       [2],
       [5],
       [8]])

In [31]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [32]:
np.array(test_matrix).reshape(2,-1).shape

(2, 4)

In [33]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [34]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

#### flat or flatten()

In [35]:
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

#### indexing

In [36]:
test_exmaple = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_exmaple

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
test_exmaple[0][0]

1

In [38]:
test_exmaple[0,0]

1

In [39]:
test_exmaple[0,0] = 10 # Matrix 0,0 에 12 할당
test_exmaple

array([[10,  2,  3],
       [ 4,  5,  6]])

In [40]:
test_exmaple[0][0] = 5 # Matrix 0,0 에 12 할당
test_exmaple[0,0]

5

#### slicing

In [41]:
test_exmaple = np.array([
    [1, 2, 5,8], [1, 2, 5,8],[1, 2, 5,8],[1, 2, 5,8]], int)
test_exmaple[:2,:] 

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [42]:
test_exmaple[:,1:3] 
test_exmaple[1,:2] 

array([1, 2])

In [43]:
test_exmaple = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
test_exmaple[:,2:] # 전체 Row의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [44]:
test_exmaple[1,1:3] # 1 Row의 1열 ~ 2열

array([7, 8])

In [45]:
test_exmaple[1:3] # 1 Row ~ 2Row의 전체

array([[ 6,  7,  8,  9, 10]])

In [46]:
a = np.arange(100).reshape(10,10)
a[:, -1].reshape(-1,1)

array([[ 9],
       [19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])

#### arange

In [48]:
np.arange(30).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [49]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [50]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [51]:
np.zeros(shape=(10,), dtype=np.int8) # 10 - zero vector 생성

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [52]:
np.zeros((2,5)) # 2 by 5 - zero matrix 생성

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
np.ones(shape=(10,), dtype=np.int8) 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [54]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
np.empty(shape=(10,), dtype=np.int8) 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [56]:
np.empty((3,5))

array([[6.91813015e-310, 4.67386312e-310, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 3.16202013e-322, 3.95252517e-322,
        4.67386319e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

In [57]:
test_matrix = np.arange(30).reshape(5,6)
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

#### eye, identity & digonal

In [59]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [61]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [63]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [66]:
np.diag(matrix, k=1)

array([1, 5])

In [67]:
np.random.uniform(0,1,10).reshape(2,5)

array([[0.10588502, 0.91994341, 0.3039931 , 0.33935742, 0.85266671],
       [0.10239351, 0.87654839, 0.6277712 , 0.7429291 , 0.02112365]])

In [68]:
np.random.normal(0,1,10).reshape(2,5)

array([[ 0.7633171 , -2.1635983 , -1.70254506, -0.7880421 , -0.82237112],
       [-1.6531154 , -0.77456854,  0.76863754, -1.32055834, -0.09203482]])

#### operation in array

In [69]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
test_array.sum(dtype=np.float)

55.0

In [71]:
test_array = np.arange(1,13).reshape(3,4)
test_array.sum()

78

In [72]:
test_array.sum(axis=1)

array([10, 26, 42])

In [73]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [74]:
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [75]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [76]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [77]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [78]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
test_array.mean(), test_array.mean(axis=0)

(6.5, array([5., 6., 7., 8.]))

In [80]:
test_array.std(), test_array.std(axis=0)

(3.452052529534663, array([3.26598632, 3.26598632, 3.26598632, 3.26598632]))

In [81]:
np.exp(test_array), np.sqrt(test_array)

(array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
        [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
        [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]),
 array([[1.        , 1.41421356, 1.73205081, 2.        ],
        [2.23606798, 2.44948974, 2.64575131, 2.82842712],
        [3.        , 3.16227766, 3.31662479, 3.46410162]]))

#### Arrary operations

In [88]:
test_a = np.array([[1,2,3],[4,5,6]], float)

In [89]:
test_a + test_a # Matrix + Matrix 연산

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [90]:
test_a - test_a # Matrix - Matrix 연산

array([[0., 0., 0.],
       [0., 0., 0.]])

In [91]:
test_a * test_a # Matrix내 element들 간 같은 위치에 있는 값들끼리 연산

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [92]:
matrix_a = np.arange(1,13).reshape(3,4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [93]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

In [94]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [9]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
test_a.transpose() 

array([[1, 4],
       [2, 5],
       [3, 6]])

In [46]:
arr = np.arange(16).reshape((2,2,4))
print(arr.transpose((0,1,2)))
print()
print()
print(arr.transpose((2,1,0)))
print()
print()
print(arr.transpose((1,0,2)))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]


[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [97]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [43]:
arr = np.arange(6).reshape(2,3)
print(arr)

arr.transpose(1,0)

[[0 1 2]
 [3 4 5]]


array([[0, 3],
       [1, 4],
       [2, 5]])

In [42]:
arr = np.arange(24).reshape(2,3,4)
print(arr)
print()
print(arr.transpose(2,1,0))
print()
print(arr.transpose(2,0,1))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]

[[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]


In [98]:
test_a.T.dot(test_a) # Matrix 간 곱셈

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

#### all & any

In [107]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [109]:
np.any(a>5), np.any(a<0)

(True, False)

In [110]:
np.all(a>5) , np.all(a < 10)

(False, True)

#### comparision operation

In [112]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b 

array([False,  True, False])

In [113]:
test_a == test_b 

array([False, False, False])

In [114]:
(test_a > test_b).any()

True

In [115]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3) # and 조건의 condition

array([ True, False, False])

In [116]:
b = np.array([True, False, True], bool)
np.logical_not(b) # NOT 조건의 condition

array([False,  True, False])

In [117]:
c = np.array([False, True, False], bool)
np.logical_or(b, c) # OR 조건의 condition

array([ True,  True,  True])

In [118]:
a

array([1., 3., 0.])

In [119]:
np.where(a > 0, 3, 2) 

array([3, 3, 2])

In [120]:
np.where(a>0)

(array([0, 1]),)

In [121]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [122]:
np.where(a>10)

(array([6, 7, 8, 9]),)

In [123]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [124]:
np.isfinite(a)

array([ True, False, False])

#### argmax & argmin

In [125]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a) , np.argmin(a)

(5, 0)

In [126]:
a=np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1) , np.argmin(a, axis=0)

(array([3, 1, 1]), array([0, 0, 2, 2]))

#### boolean index

In [128]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [129]:
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [130]:
condition = test_array < 3 
test_array[condition]

array([1., 0., 2.])

In [131]:
A = np.array([
[12, 13, 14, 12, 16, 14, 11, 10,  9],
[11, 14, 12, 15, 15, 16, 10, 12, 11],
[10, 12, 12, 15, 14, 16, 10, 12, 12],
[ 9, 11, 16, 15, 14, 16, 15, 12, 10],
[12, 11, 16, 14, 10, 12, 16, 12, 13],
[10, 15, 16, 14, 14, 14, 16, 15, 12],
[13, 17, 14, 10, 14, 11, 14, 15, 10],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 17, 19, 16, 17, 18, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 12, 14, 11, 12, 14, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11]])
B = A < 15
B.astype(np.int)

array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1]])

#### fancy index

In [132]:
a = np.array([2, 4, 6, 8], float)

In [133]:
a[a>4] 

array([6., 8.])

In [134]:
a.take(b) #take 함수: bracket index와 같은 효과

array([4., 2., 4.])

In [135]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c] # b를 row index, c를 column index로 변환하여 표시함

array([ 1.,  4., 16., 16.,  4.])

In [136]:
a = np.array([[1, 4], [9, 16]], float)
a[b]

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 9., 16.],
       [ 9., 16.],
       [ 1.,  4.]])